services:
  backend:
    build:
      context: backend
      target: builder
    stop_signal: SIGINT
    env_file:
      - ./.env
    environment:
      - FLASK_SERVER_PORT=9091
    # volumes:
    #   - ./backend:/src

  proxy:
    # image: nginx
    build:
      context: proxy
    env_file:
      - ./.env
    environment:
      FLASK_SERVER_ADDR: backend:9091
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
    # volumes:
    #   - ./proxy/nginx.conf:/tmp/nginx.conf
    # command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8091:80
    depends_on:
      - backend
